services:
  database:
    build: ./db/
   
  app:
    build: .
    container_name: friendship-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports: 
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - database
